version: '3.7'

services:
  ecommer:
    build: .  # Sử dụng Dockerfile để build
    shm_size: '2gb'  # Thêm dòng này để tránh lỗi bộ nhớ Chrome
    volumes:
      - ./scraping:/opt/airflow/scraping
      - ./parsing:/opt/airflow/parsing
      - ./dags:/opt/airflow/dags
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./keyword.csv:/opt/airflow/keyword.csv
      - ./config:/opt/airflow/config
      - ./storage:/opt/airflow/storage
    ports:
      - 8080:8080
    command: bash -c '(airflow db init && airflow users create --username admin --password admin --firstname The --lastname Xuyen --role Admin --email thexuyentrinh@gmail.com); airflow webserver & airflow scheduler'
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    env_file:
      - .env
